package envformat_test

import (
	"bytes"
	"strings"
	"testing"

	"github.com/vaultline/vaultline/internal/envformat"
)

func TestWrite_SortedKeys(t *testing.T) {
	f := envformat.New(envformat.Options{SortKeys: true})
	secrets := map[string]string{"ZEBRA": "1", "ALPHA": "2", "MANGO": "3"}
	var buf bytes.Buffer
	if err := f.Write(&buf, secrets); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	lines := strings.Split(strings.TrimSpace(buf.String()), "\n")
	if lines[0] != "ALPHA=2" || lines[1] != "MANGO=3" || lines[2] != "ZEBRA=1" {
		t.Errorf("unexpected order: %v", lines)
	}
}

func TestWrite_QuotesValuesWithSpaces(t *testing.T) {
	f := envformat.New(envformat.DefaultOptions())
	secrets := map[string]string{"MSG": "hello world"}
	var buf bytes.Buffer
	if err := f.Write(&buf, secrets); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(buf.String(), `MSG="hello world"`) {
		t.Errorf("expected quoted value, got: %s", buf.String())
	}
}

func TestWrite_Header(t *testing.T) {
	f := envformat.New(envformat.Options{SortKeys: true, Header: "generated by vaultline"})
	var buf bytes.Buffer
	if err := f.Write(&buf, map[string]string{"A": "1"}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.HasPrefix(buf.String(), "# generated by vaultline") {
		t.Errorf("missing header: %s", buf.String())
	}
}

func TestWrite_GroupByPrefix_InsertsBlankLines(t *testing.T) {
	f := envformat.New(envformat.Options{SortKeys: true, GroupByPrefix: true})
	secrets := map[string]string{
		"APP_HOST": "localhost",
		"APP_PORT": "8080",
		"DB_HOST":  "db",
		"DB_PORT":  "5432",
	}
	var buf bytes.Buffer
	if err := f.Write(&buf, secrets); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(buf.String(), "\n\n") {
		t.Errorf("expected blank line between groups, got:\n%s", buf.String())
	}
}

func TestWrite_EmptySecrets(t *testing.T) {
	f := envformat.New(envformat.DefaultOptions())
	var buf bytes.Buffer
	if err := f.Write(&buf, map[string]string{}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if buf.Len() != 0 {
		t.Errorf("expected empty output, got: %q", buf.String())
	}
}

func TestWrite_QuotesValuesWithHash(t *testing.T) {
	f := envformat.New(envformat.DefaultOptions())
	secrets := map[string]string{"TOKEN": "abc#123"}
	var buf bytes.Buffer
	if err := f.Write(&buf, secrets); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(buf.String(), `TOKEN="abc#123"`) {
		t.Errorf("expected quoted hash value, got: %s", buf.String())
	}
}
